apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echo-server-deployment
  labels:
    app: echo-server
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar-injector.hipspec.com/inject: "haystack-agent"
        sidecar-injector.hipspec.com/some-api-key: "6feab492-fc9b-4c38-b50d-3791718c8203"
      labels:
        app: echo-server
    spec:
      containers:
        - name: echo-server
          image: hashicorp/http-echo
          imagePullPolicy: IfNotPresent
          args:
            - -listen=:8080
            - -text="hello world"
